title: CEDA Technical Blog
description: Technical blog from CEDA. Projects from the development and data management teams. Projects here may be experimental and unfinished.
show_excerpts: true

plugins:
  - jekyll-feed