title: CEDA Technical Blog
description: Technical blog by the Centre for Environmental Data Analysis (CEDA). These posts are written by members of the development and data management teams about work being undertaken in CEDA. Projects described here may be experimental and unfinished.
show_excerpts: true

plugins:
  - jekyll-feed